model_list:
  - model_name: gpt-4.1
    litellm_params:
      model: github_copilot/gpt-4.1
      extra_headers:
        {
          "Editor-Version": "vscode/1.155.1",
          "Copilot-Integration-Id": "vscode-chat",
          "editor-plugin-version": "copilot/1.155.0",
          "user-agent": "GithubCopilot/1.155.0",
        }
  - model_name: claude-sonnet-4.5
    litellm_params:
      model: github_copilot/claude-sonnet-4.5
      extra_headers:
        {
          "Editor-Version": "vscode/1.155.1",
          "Copilot-Integration-Id": "vscode-chat",
          "editor-plugin-version": "copilot/1.155.0",
          "user-agent": "GithubCopilot/1.155.0",
        }
